apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-scratch
  namespace: argocd
spec:
  destination: # Where should my application deployed
    namespace: default
    server: https://kubernetes.default.svc # Default cluster
  project: default
  source:
    chart: sealed-secrets
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    helm:
      releaseName: sealed-secrets
    targetRevision: 1.16.1
