apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applcation-scratch
spec:
  destination: # Where should my application deployed
    namespace: default
    server: https://kubernetes.default.svc # Default cluster
  project: default
  source:
    path: nginx-helm # Path of manifest under repository
    repoURL: https://github.com/HarshPanchal18/argocd-application.git
    targetRevision: main # Branch name
