apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 2 # Update the replica count to 2
  selector:
    matchLabels:
      app: web
  template:
    spec:
      containers:
      - name: nginx
        image: harshpanchal18/nginx-argo:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "200m" # Lower CPU limit to 200m (0.2 CPU cores)
            memory: "256Mi" # Lower memory limit to 256 MiB
          requests:
            cpu: "100m" # Lower CPU request to 100m (0.1 CPU cores)
            memory: "128Mi"
