apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: # Kustomize needs to know the path of base files.
  - ../../base
  # - "https://raw.githubusercontent.com/HarshPanchal18/DevOps/refs/heads/main/Kubernetes/kustomize/base/deployment.yaml"

patches:
  - path: deployment-dev.yaml
  - path: service-dev.yaml